# Generated by Django 5.1.6 on 2025-06-26 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0005_alter_message_created_at_conversation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='last_message_at',
        ),
    ]
