# Generated by Django 5.1.6 on 2025-03-30 13:00

import welcome.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0009_profile_website_alter_profile_cover_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to='welcome.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to=welcome.models.cover_photo_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/default.jpg', upload_to=welcome.models.user_profile_picture_path),
        ),
    ]
