# Generated by Django 5.1.6 on 2025-04-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0012_alter_profile_cover_photo_and_more'),
    ]

    operations = [
           migrations.AddField(
            model_name='post',
            name='media_file',
            field=models.FileField(null=True, upload_to='posts/'),
        ),
        migrations.AddField(
            model_name='post',
            name='media_type',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
