# Generated by Django 5.1.6 on 2025-04-01 14:42

from django.db import migrations, models
import os
from django.conf import settings



def populate_media(apps, schema_editor):
    Post = apps.get_model('welcome', 'Post')
    
    # Create default media file path
    default_media = os.path.join(settings.MEDIA_ROOT, 'posts/default.jpg')
    os.makedirs(os.path.dirname(default_media), exist_ok=True)
    
    for post in Post.objects.all():
        if not post.media_file:  # Only if null
            post.media_file = 'posts/default.jpg'
            post.media_type = 'image'
            post.save()

class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0013_auto_20250401_1840'),
    ]

    operations = [
        migrations.RunPython(populate_media),
    ]
