# Generated by Django 5.1.6 on 2025-04-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0014_populate_media_fields'),
    ]

    operations = [
         migrations.AlterField(
            model_name='post',
            name='media_file',
            field=models.FileField(upload_to='posts/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='media_type',
            field=models.CharField(max_length=5),
        ),
    ]
