# Generated by Django 5.1.6 on 2025-04-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0015_make_media_fields_non_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='filter_effect',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
