# Generated by Django 5.1.6 on 2025-04-01 15:01

import welcome.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0016_add_filter_effect_to_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='duration',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='post',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=5),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to=welcome.models.cover_photo_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/default.jpg', upload_to=welcome.models.user_profile_picture_path),
        ),
         migrations.AddField(
            model_name='post',
            name='filter_effect',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='duration',
            field=models.PositiveIntegerField(default=15),  # Default of 15 seconds
        ),
    ]
